const CONFIG = {
  SHEET_ID: '1l9vBwJzPTvK92EEH6kpATD931HEwnUBS5EsA78xBWZc',
  WHEEL_CIRCUMFERENCE_M: 0.88,
  UPLOAD_INTERVAL_S: 30,
  REFRESH_INTERVAL_MS: 15000,
  COMFORT_TEMP_MIN: 24,
  COMFORT_TEMP_MAX: 27,
  SMOOTHING_WINDOW: 3,
  SPEED_THRESHOLDS: { idle: 2, active: 5, running: 8 },
};
